<testsuite tests="3"><testcase classname=" python Homeautomation_Appium.py " name="python Homeautomation_Appium.py"><failure type="NA">'  File Homeautomation_Appium.py, line 39, in setUpn', 'n',     self.device1 = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps1)n, 'n', '  File C:Program FilesPython35libsite-packagesseleniumwebdriverremotewebdriver.py, line 91, in __init__n', 'n', '    self.start_session(desired_capabilities, browser_profile)n', 'n', '  File C:Program FilesPython35libsite-packagesseleniumwebdriverremotewebdriver.py, line 173, in start_sessionn', 'n',     'desiredCapabilities': desired_capabilities,n, 'n', '  File C:Program FilesPython35libsite-packagesseleniumwebdriverremotewebdriver.py, line 231, in executen', 'n', '    response = self.command_executor.execute(driver_command, params)n', 'n', '  File C:Program FilesPython35libsite-packagesseleniumwebdriverremoteremote_connection.py, line 395, in executen', 'n', '    return self._request(command_info[0], url, body=data)n', 'n', '  File C:Program FilesPython35libsite-packagesseleniumwebdriverremoteremote_connection.py, line 463, in _requestn', 'n', '    resp = opener.open(request, timeout=self._timeout)n', 'n', '  File C:Program FilesPython35liburllibrequest.py, line 465, in openn', 'n', '    response = self._open(req, data)n', 'n', '  File C:Program FilesPython35liburllibrequest.py, line 483, in _openn', 'n',     '_open', req)n, 'n', '  File C:Program FilesPython35liburllibrequest.py, line 443, in _call_chainn', 'n', '    result = func(*args)n', 'n', '  File C:Program FilesPython35liburllibrequest.py, line 1268, in http_openn', 'n', '    return self.do_open(http.client.HTTPConnection, req)n', 'n', '  File C:Program FilesPython35liburllibrequest.py, line 1243, in do_openn', 'n', '    r = h.getresponse()n', 'n', '  File C:Program FilesPython35libhttpclient.py, line 1174, in getresponsen', 'n', '    response.begin()n', 'n', '  File C:Program FilesPython35libhttpclient.py, line 282, in beginn', 'n', '    version, status, reason = self._read_status()n', 'n', '  File C:Program FilesPython35libhttpclient.py, line 243, in _read_statusn', 'n', '    line = str(self.fp.readline(_MAXLINE + 1), iso-8859-1)n', 'n', '  File C:Program FilesPython35libsocket.py, line 575, in readinton', 'n', '    return self._sock.recv_into(b)n', 'n', 'ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote hostn', 'n', 'n', 'n', '----------------------------------------------------------------------n', 'n', 'Ran 1 test in 0.294sn', 'n', 'n', 'n', 'FAILED (errors=1)n', 'n', 'En', 'n', '======================================================================n', 'n', 'ERROR: testscript (__main__.cpaas_pyTest)n', 'n', '----------------------------------------------------------------------n', 'n', 'Traceback (most recent call last):n', 'n', '  File Homeautomation_AWS_API.py, line 50, in testscriptn', 'n', '    ss = subprocess.Popen(abc, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)n', 'n', '  File C:Program FilesPython35libsubprocess.py, line 950, in __init__n', 'n', '    restore_signals, start_new_session)n', 'n', '  File C:Program FilesPython35libsubprocess.py, line 1220, in _execute_childn', 'n', '    startupinfo)n', 'n', 'FileNotFoundError: [WinError 2] The system cannot find the file specifiedn', 'n', 'n', 'n', '----------------------------------------------------------------------n', 'n', 'Ran 1 test in 5.336sn', 'n', 'n', 'n', 'FAILED (errors=1)n', 'n', '  File jiraisuuecreator.py, line 1n', 'n', '    int i = 1n', 'n', '        ^n', 'n', 'SyntaxError: invalid syntaxn', 'n'</failure></testcase><testcase classname=" python Homeautomation_AWS_API.py " name="python Homeautomation_AWS_API.py"><failure type="NA">'  File Homeautomation_AWS_API.py, line 50, in testscriptn', 'n', '    ss = subprocess.Popen(abc, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)n', 'n', '  File C:Program FilesPython35libsubprocess.py, line 950, in __init__n', 'n', '    restore_signals, start_new_session)n', 'n', '  File C:Program FilesPython35libsubprocess.py, line 1220, in _execute_childn', 'n', '    startupinfo)n', 'n', 'FileNotFoundError: [WinError 2] The system cannot find the file specifiedn', 'n', 'n', 'n', '----------------------------------------------------------------------n', 'n', 'Ran 1 test in 5.336sn', 'n', 'n', 'n', 'FAILED (errors=1)n', 'n', '  File jiraisuuecreator.py, line 1n', 'n', '    int i = 1n', 'n', '        ^n', 'n', 'SyntaxError: invalid syntaxn', 'n'</failure></testcase><testcase classname=" python jiraisuuecreator.py " name="python jiraisuuecreator.py"><failure type="NA">'  File jiraisuuecreator.py, line 1n', 'n', '    int i = 1n', 'n', '        ^n', 'n', 'SyntaxError: invalid syntaxn', 'n'</failure></testcase></testsuite>